### ISSUE TITLE
Dacument fiture

### ISSUE THREAD

**Issue by OPLegend32** [PRABAKARAN32/Whatsus-chatingapp#9]
For Enhanceing the app perfamence and user intraction I sigust you that to incloud the Dacument sharing feture i.e pdf.

**Comment by PRABAKARAN32** [comment]
Thank you for your suggestion we will add as soon as possible. Keep supporting us.

**Comment by PRABAKARAN32** [comment]
We have included the new feature. Keep supporting us.
